### PR TITLE
Jonathanmaw/session 4

### LINKED ISSUE #1: Session 4 homework
Overall goal: nicer CLI, syntax checking

**Don't forget to do this in a Pull Request**

* [x] CLI
  * [x] Positional argument PROGRAM
  * [x] --help and --version
  * [x] CLI handling in a separate "src/cli.rs" module
  * [x] optional argument '-c' or '--cells', nonzero numeric argument for number of cells in the tape
  * [x] optional argument '-e' or '--extensible', allows auto-extending the tape
    * [x] '--cells 0' should error.
* [x] Validate program
  * [x] A function to find unmatched brackets - report first unbalanced brackets found
  * [x] Any intermediate state generated while working this out should be stored in the interpreter
    This requires the checking function to take a `&mut self` instead of `&self`.
  * [x] Don't forget to call this validator inside main and report errors.
  * [x] Tests and documentation for the validator.
* [x] Nicer exit
  * [x] Cli has a `run_bft()` function, taking the struct generated by arg parsing and returning a
        Result as usual.
  * [x] `fn main() {}`  calls `run_bft()`, if there's an error it formats the error appropriately
    and returns a failure code of 1.
    Example error: `bft: Error in input file foo.bf, no close bracket found matching bracket at
    line 4 column 8`

### PR DESCRIPTION
**Pull request by maw3193**
Resolves #1

### CODE REVIEW

File: bft/bft_types/src/lib.rs [hunk 1]
```diff
@@ -107,7 +107,7 @@ impl Program {
     /// ```
     // TODO: Path to AsRef<Path>
     // new<P: AsRef<Path>>(path: P)
-    pub fn from_file<T: AsRef<Path> + ToString + Copy>(file: T) -> std::io::Result<Program> {
+    pub fn from_file<T: AsRef<Path> + Copy + Into<PathBuf>>(file: T) -> std::io::Result<Program> {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: I think you've overcomplicated this constraint very much.  You should be able to do everything with just `AsRef<Path>` no need for `+ Copy + Into<PathBuf>`

File: bft/bft_types/src/lib.rs [hunk 2]
```diff
@@ -123,7 +123,7 @@ impl Program {
     /// let prog: bft_types::Program = bft_types::Program::new(&filename, &text);
     /// ```
     // NOTE: I tried to use the generic `U: AsRef<str> + BufRead>` but then text.lines() was fallible.
-    pub fn new<T: AsRef<Path> + ToString>(filename: T, text: &str) -> Program {
+    pub fn new<T: AsRef<Path> + Into<PathBuf>>(filename: T, text: &str) -> Program {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: Again here `AsRef<Path>` should be plenty

File: bft/bft_types/src/lib.rs [hunk 3]
```diff
@@ -139,12 +139,12 @@ impl Program {
...
         // If I can read them I can print the closest I can to its representation.
         Program {
-            file: filename.to_string(),
+            file: filename.into(),
             instructions,
         }
     }
 
-    pub fn file(&self) -> &str {
+    pub fn file(&self) -> &PathBuf {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: Don't use `&PathBuf` here, it's "wasteful of type" instead use `&Path`

File: bft/bft_types/src/lib.rs [hunk 4]
```diff
@@ -156,7 +156,7 @@ impl Program {
 impl fmt::Display for Program {
     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
         for instruction in self.instructions() {
-            writeln!(f, "{}:{}", self.file(), instruction,)?
+            writeln!(f, "{}:{}", self.file().to_string_lossy(), instruction,)?
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: Paths have `.display()` which is more efficient and also less icky than `.to_string_lossy()`

File: bft/bft_interp/src/lib.rs [hunk 5]
```diff
@@ -32,6 +32,17 @@ impl<T> Machine<T> {
...
+    /// Checks whether a provided program is valid Brainfuck code
+    ///
+    /// As it's a very thin wrapper around DecoratedProgram::from_program,
+    /// see that for examples of how this is used.
+    pub fn validate(&self, prog: &Program) -> Result<(), ParseError> {
+        // Reuse existing parsing logic, throwing away the success
+        // and propagating any errors
+        DecoratedProgram::from_program(prog)?;
+        Ok(())
+    }
```
Comment (danielsilverstone-ct) [inline bft/bft_interp/src/lib.rs:45]: I'll admit I wasn't expecting to see this at all here.

Given the implication of a `DecoratedProgram` I would have expected to see the conversion in your main code, and then a change to the interpreter VM to take one of those directly.

File: bft/bft_types/src/lib.rs [hunk 6]
```diff
@@ -6,9 +6,10 @@ use std::fs::File;
 use std::io::{BufReader, Read};
 use std::path::{Path, PathBuf};
 use std::string::String;
+use thiserror::Error;
 
 /// An enum of every possible instruction Brainfuck can execute
-#[derive(Debug, PartialEq)]
+#[derive(Debug, PartialEq, Clone)]
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: This enum is trivial and so could also be `Copy` if you wanted.

File: bft/bft_types/src/lib.rs [hunk 7]
```diff
@@ -63,7 +64,7 @@ impl fmt::Display for RawInstruction {
 }
 
 /// A brainfuck instruction with added context of where it exists within the codebase
-#[derive(Debug)]
+#[derive(Debug, Clone)]
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: Ditto, this struct is trivial so could also be `Copy` if you wanted.

File: bft/bft_types/src/lib.rs [hunk 8]
```diff
@@ -89,6 +90,137 @@ impl fmt::Display for PositionedInstruction {
         write!(f, "{}:{} {}", self.line, self.character, self.instruction)
     }
 }
+/// Instructions that have been processed into a form useful to an interpreter
+pub enum DecoratedInstruction {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs:94]: This type is quite complex, I'm not sure why you need it to be this much.  eg. do you need the `closer` and `opener` as well as the indices?

File: bft/bft_types/src/lib.rs [hunk 9]
```diff
@@ -89,6 +90,137 @@ impl fmt::Display for PositionedInstruction {
...
+    Instruction(PositionedInstruction),
+    /// An open-bracket instruction that gets replaced when the loop is closed
+    ///
+    /// This is expected to only exist as a temporary implementation detail.
+    PlaceholderOpenBracket,
+}
+
+/// A program that's been processed into a form useful to an interpreter
+/// Compared to a Program, this has the additional constraint that the code must be valid Brainfuck.
+pub struct DecoratedProgram {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs:117]: I like the idea that you've gone for using types to enforce the validity invariant.

File: bft/bft_types/src/lib.rs [hunk 10]
```diff
@@ -89,6 +90,137 @@ impl fmt::Display for PositionedInstruction {
...
+        // NOTE: Used a match for lack of a better way of comparing an enum
+        assert!(decorated_instructions.iter().all(|i| !matches!(i, DecoratedInstruction::PlaceholderOpenBracket)));
+
+        Ok(DecoratedProgram {
+            file: prog.file().clone(),
+            decorated_instructions,
+        })
+    }
+
+    pub fn file(&self) -> &PathBuf {
```
Comment (danielsilverstone-ct) [inline bft/bft_types/src/lib.rs]: Use `&Path` here.

File: bft/src/main.rs [hunk 11]
```diff
@@ -7,6 +7,6 @@ fn main() -> Result<(), Box<dyn std::error::Error>> {
     let args = cli::Cli::parse();
     let prog = Program::from_file(&args.program)?;
     let machine: Machine<u8> = Machine::new(args.cells, args.extensible);
-    machine.print_program(&prog);
+    machine.validate(&prog)?;
```
Comment (danielsilverstone-ct) [inline bft/src/main.rs]: Aha, here's why you no longer output the code, I was expecting both behaviours, not just the validation.

File: bft/src/main.rs [hunk 12]
```diff
@@ -1,12 +1,10 @@
...
-fn main() -> Result<(), Box<dyn std::error::Error>> {
-    let args = cli::Cli::parse();
-    let prog = Program::from_file(&args.program)?;
-    let machine: Machine<u8> = Machine::new(args.cells, args.extensible);
-    machine.validate(&prog)?;
-    Ok(())
+fn main() {
+    match cli::run_bft() {
+        Err(e) => {
+            println!("{}: Error: {}", std::env::args().nth(0).unwrap(), e.to_string())
```
Comment (danielsilverstone-ct) [inline bft/src/main.rs]: You're missing a non-zero exit here.

File: bft/src/main.rs [hunk 13]
```diff
@@ -1,14 +1,7 @@
...
-        Err(e) => {
-            println!(
-                "{}: Error: {}",
-                std::env::args().nth(0).unwrap(),
-                e.to_string()
-            )
-        }
-        Ok(_) => (),
+    if let Err(e) = cli::run_bft() {
+        println!("{}: Error: {}", std::env::args().next().unwrap(), e,)
```
Comment (danielsilverstone-ct) [inline bft/src/main.rs]: If you weren't missing the non-zero exit code I mentioned; this whole commit would have been unnecessary

**Review by danielsilverstone-ct — CHANGES_REQUESTED** [review]
Review was done commit-by-commit, generally very good, see final comments in email.
